---
- name: Openclassrooms P5 EDO deployment
  hosts: all
  become: true

  vars:
    app_source_dir: "olympic-games-starter/"
    app_target_dir: "/var/www/html/olympic-games-starter"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install nginx
      apt:
        name: 
          - nginx
        state: present

    - name: Remove existing directory /olympic-games-starter
      file:
        path: "{{ app_target_dir }}"
        state: absent

    - name: Copy static application files in /olympic-games-starter
      copy:
        src: "{{ app_source_dir }}"
        dest: "{{ app_target_dir }}"
      notify: Restart nginx

    - name: Apply nginx configuration
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart nginx

    - name: Validate nginx configuration
      command: nginx -t
      changed_when: false

    - name: Ensure nginx is started
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    # Implémenter ici le handler redémarrant automatiquement le serveur Nginx lorsque le playbook
    # opère une modification de la configuration du serveur.

    - name: Restart nginx
      service:
        name: nginx
        state: restarted